# .github/workflows/commitlint.yml
name: Commitlint (central template)

# doesn't need workflow call, only use : for nested data
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    # calls your central workflow
    uses: takara-ai/.github/.github/workflows/commit.yml@main
    # inherit the caller’s GITHUB_TOKEN so Commitlint can read PRs/commits
    secrets: inherit
    # this is neccessary to pass to central workflow