name: Commit
on:
  workflow_call:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read
  pull-requests: read

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate Commitlint config
        run: |
          cat > commitlint.config.mjs << 'EOF'
          export default {
            extends: ['@commitlint/config-conventional'],
            rules: {
              // disable only the subject-case rule
              'subject-case': [0],
            },
          };
          EOF

      - name: Lint PR commits
        uses: wagoid/commitlint-github-action@v6
        with:
          configFile: commitlint.config.mjs

  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check for Python files
        id: check-python
        run: |
          if git ls-files "*.py" | head -1; then
            echo "python_detected=true" >> $GITHUB_OUTPUT
          else
            echo "python_detected=false" >> $GITHUB_OUTPUT
          fi

      - name: Run Ruff
        if: steps.check-python.outputs.python_detected == 'true'
        uses: astral-sh/ruff-action@v3
        with:
          args: check --output-format=github

      - name: No Python files found
        if: steps.check-python.outputs.python_detected == 'false'
        run: echo "No Python files detected. Ruff linting skipped."
