name: Commit
on:
  workflow_call:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read
  pull-requests: read

jobs:
  commits:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Clone commit-lint repository
        run: git clone https://github.com/takara-ai/commit-lint.git
      - name: Run commitlint
        run: |
          cd commit-lint
          go run .
        env:
          ALLOW_CAPITAL_SUBJECT: "true"

  python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Ruff
        if: hashFiles('**/*.py') != ''
        uses: astral-sh/ruff-action@v3
        with:
          args: check --output-format=github

  golang:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        if: hashFiles('**/*.go') != ''
        uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Run golangci-lint
        if: hashFiles('**/*.go') != ''
        uses: golangci/golangci-lint-action@v8

  js:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Biome
        if: hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') != ''
        uses: biomejs/setup-biome@v2
        with:
          version: latest
      - name: Run Biome
        if: hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') != ''
        run: biome ci --reporter=github .
