name: Release Please (Reusable)

on:
  workflow_call:
    inputs:
      branch:
        description: 'Branch to run on'
        required: false
        type: string
        default: 'main'
      config-file:
        description: 'Path to release-please config file'
        required: false
        type: string
        default: '.release-please-config.json'
    secrets:
      token:
        description: 'GitHub token for release-please'
        required: true

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.token }}
          config-file: ${{ inputs.config-file }} 