name: release-please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    uses: takara-ai/.github/workflow-templates/release-please.yml@main 
