name: release-please

on:
  workflow_call:
    inputs:
      release-type:
        description: "Release Please release-type"
        required: false
        type: string
        default: simple
  # Optional: keep this only if you also want the template repo itself to run on pushes
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          release-type: ${{ inputs.release-type }}
