name: release-please

on:
  push:
    branches:
      - main

jobs:
  release-please:
    uses: ./.github/workflows/release-please-reusable.yml
    with:
      token: ${{ secrets.MY_RELEASE_PLEASE_TOKEN }} 
