# .github/workflows/release-please.yml

name: release-please

workflow_call:
on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          release-type: simple
          # token input is omitted, so it defaults to GITHUB_TOKEN
