name: Release Please (Reusable)

on:
  workflow_call:
    inputs:
      token:
        description: 'GitHub token for release-please'
        required: true
        type: string
      branch:
        description: 'Branch to run on'
        required: false
        type: string
        default: 'main'
      config-file:
        description: 'Path to release-please config file'
        required: false
        type: string
        default: '.release-please-config.json'

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/release-please
        with:
          token: ${{ inputs.token }}
          config-file: ${{ inputs.config-file }} 