name: release-please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/release-please
        with:
          token: ${{ secrets.MY_RELEASE_PLEASE_TOKEN }} 
