name: release-please

on:
  workflow_call:
    inputs:
      release-type:
        description: "Release Please release-type"
        required: false
        type: string
        default: simple
      config-file:
        description: "Repository Release Please manifest configuration path"
        required: false
        type: string
        default: ""
      manifest-file:
        description: "Repository Release Please version manifest path"
        required: false
        type: string
        default: ".release-please-manifest.json"

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ inputs.config-file != '' && steps.manifest.outputs.release_created || steps.release.outputs.release_created }}
      tag_name: ${{ inputs.config-file != '' && steps.manifest.outputs.tag_name || steps.release.outputs.tag_name }}
      version: ${{ inputs.config-file != '' && steps.manifest.outputs.version || steps.release.outputs.version }}
    steps:
      - id: release
        if: ${{ inputs.config-file == '' }}
        uses: googleapis/release-please-action@v4
        with:
          release-type: ${{ inputs.release-type }}
      - id: manifest
        if: ${{ inputs.config-file != '' }}
        uses: googleapis/release-please-action@v4
        with:
          config-file: ${{ inputs.config-file }}
          manifest-file: ${{ inputs.manifest-file }}
