name: Release Please (Reusable)

on:
  workflow_call:
    inputs:
      token:
        description: 'GitHub token for release-please'
        required: true
        type: string
      branch:
        description: 'Branch to run on'
        required: false
        type: string
        default: 'main'

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          token: ${{ inputs.token }} 